// <auto-generated />
using System;
using Gerente.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gerente.Infra.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gerente.Domain.Entities.ControleVersao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlteradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlteradoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ControleVersao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PessoaSetor", b =>
                {
                    b.Property<int>("ServidoresId")
                        .HasColumnType("int");

                    b.Property<int>("SetoresId")
                        .HasColumnType("int");

                    b.HasKey("ServidoresId", "SetoresId");

                    b.HasIndex("SetoresId");

                    b.ToTable("PessoaSetor");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Aditivo", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAditivo")
                        .HasColumnType("datetime2");

                    b.Property<int>("MesesAcrescidos")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasIndex("ContratoId");

                    b.ToTable("Aditivo");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Agendamento", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilaProcedimentoId")
                        .HasColumnType("int");

                    b.Property<int>("HoraInicio")
                        .HasColumnType("int");

                    b.Property<int>("Membro")
                        .HasColumnType("int");

                    b.Property<string>("MensagemNotificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePessoaConfirmacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Realizado")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("FilaProcedimentoId");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Cargo", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecretariaId")
                        .HasColumnType("int");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.HasIndex("SecretariaId");

                    b.HasIndex("SetorId");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Contrato", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<DateTime>("DataContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFinalVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("ModalidadeLicitacao")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NumeroLicitacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("SistemaLicitacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoInstrumento")
                        .HasColumnType("int");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.ControleVersaoEndereco", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("ControleVersaoEndereco");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Documento", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<int>("AditivoId")
                        .HasColumnType("int");

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasIndex("AditivoId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Especialidade", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.ToTable("Especialidade");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Estado", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.FilaProcedimento", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<bool>("LadoDireito")
                        .HasColumnType("bit");

                    b.Property<bool>("LadoEsquerdo")
                        .HasColumnType("bit");

                    b.Property<int>("LocalProcedimentoId")
                        .HasColumnType("int");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<int>("ProcedimentoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("LocalProcedimentoId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProcedimentoId");

                    b.ToTable("FilaProcedimento");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Medico", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<int>("LocalProcedimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasIndex("LocalProcedimentoId");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Municipio", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasIndex("EstadoId");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Procedimento", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<bool>("DoisMembros")
                        .HasColumnType("bit");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<int>("NaturezaProcedimento")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TempoDuracao")
                        .HasColumnType("datetime2");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("Procedimento");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Setor", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SecretariaId")
                        .HasColumnType("int");

                    b.HasIndex("SecretariaId");

                    b.ToTable("Setor");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Telefone", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersao");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("PessoaResponsavel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SecretariaId")
                        .HasColumnType("int");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTelefone")
                        .HasColumnType("int");

                    b.HasIndex("PessoaId");

                    b.HasIndex("SecretariaId");

                    b.HasIndex("SetorId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("Gerente.Infra.Data.Models.Usuario", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FotoExtensao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Secretaria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SecretariaId")
                        .HasColumnType("int");

                    b.Property<string>("Setor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.LocalProcedimento", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersaoEndereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.ToTable("LocalProcedimento");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Pessoa", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersaoEndereco");

                    b.Property<string>("CartaoFundhacre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CartaoSus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NaturezaJuridica")
                        .HasColumnType("int");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.Property<int>("SecretariaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasIndex("CartaoFundhacre")
                        .IsUnique()
                        .HasFilter("[CartaoFundhacre] IS NOT NULL");

                    b.HasIndex("CartaoSus")
                        .IsUnique()
                        .HasFilter("[CartaoSus] IS NOT NULL");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("[Cpf] IS NOT NULL");

                    b.HasIndex("PessoaId");

                    b.HasIndex("SecretariaId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Secretaria", b =>
                {
                    b.HasBaseType("Gerente.Domain.Entities.ControleVersaoEndereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeSimplificado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable("Secretaria");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PessoaSetor", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("ServidoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Setor", null)
                        .WithMany()
                        .HasForeignKey("SetoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Aditivo", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Aditivos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Aditivo", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.FilaProcedimento", "FilaProcedimento")
                        .WithMany("Agendamentos")
                        .HasForeignKey("FilaProcedimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Agendamento", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("FilaProcedimento");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Cargo", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Cargo", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Secretaria", "Secretaria")
                        .WithMany("Cargos")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Setor", "Setor")
                        .WithMany("Cargos")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secretaria");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.Pessoa", "Fornecedor")
                        .WithMany("Contratos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Contrato", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.ControleVersaoEndereco", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.Estado", "Estado")
                        .WithMany("ControleVersaoEnderecos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.ControleVersaoEndereco", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Municipio", "Municipio")
                        .WithMany("ControleVersaoEnderecos")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Documento", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.Aditivo", "Aditivo")
                        .WithMany("Documentos")
                        .HasForeignKey("AditivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Documentos")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Documento", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Documentos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aditivo");

                    b.Navigation("Contrato");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Especialidade", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Especialidade", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Estado", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Estado", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gerente.Domain.Entities.FilaProcedimento", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.Especialidade", "Especialidade")
                        .WithMany("FilaProcedimentos")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.FilaProcedimento", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.LocalProcedimento", "LocalProcedimento")
                        .WithMany("FilaProcedimentos")
                        .HasForeignKey("LocalProcedimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Medico", "Medico")
                        .WithMany("FilaProcedimentos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Pessoa", "Paciente")
                        .WithMany("FilaProcedimentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Procedimento", "Procedimento")
                        .WithMany("FilaProcedimentos")
                        .HasForeignKey("ProcedimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("LocalProcedimento");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");

                    b.Navigation("Procedimento");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Medico", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Medico", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.LocalProcedimento", "LocalProcedimento")
                        .WithMany("Medicos")
                        .HasForeignKey("LocalProcedimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalProcedimento");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Municipio", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Procedimento", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.Especialidade", "Especialidade")
                        .WithMany("Procedimentos")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Procedimento", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Setor", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Setor", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Secretaria", "Secretaria")
                        .WithMany("Setores")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Telefone", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersao", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Telefone", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Secretaria", "Secretaria")
                        .WithMany("Telefones")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Setor", "Setor")
                        .WithMany("Telefones")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Secretaria");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.LocalProcedimento", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersaoEndereco", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.LocalProcedimento", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Pessoa", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersaoEndereco", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Pessoa", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Gerente.Domain.Entities.Pessoa", null)
                        .WithMany("Acompanhantes")
                        .HasForeignKey("PessoaId");

                    b.HasOne("Gerente.Domain.Entities.Secretaria", "Secretaria")
                        .WithMany("Servidores")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Secretaria", b =>
                {
                    b.HasOne("Gerente.Domain.Entities.ControleVersaoEndereco", null)
                        .WithOne()
                        .HasForeignKey("Gerente.Domain.Entities.Secretaria", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Aditivo", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Aditivos");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Especialidade", b =>
                {
                    b.Navigation("FilaProcedimentos");

                    b.Navigation("Procedimentos");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Estado", b =>
                {
                    b.Navigation("ControleVersaoEnderecos");

                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.FilaProcedimento", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Medico", b =>
                {
                    b.Navigation("FilaProcedimentos");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("ControleVersaoEnderecos");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Procedimento", b =>
                {
                    b.Navigation("FilaProcedimentos");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Setor", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.LocalProcedimento", b =>
                {
                    b.Navigation("FilaProcedimentos");

                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Acompanhantes");

                    b.Navigation("Contratos");

                    b.Navigation("Documentos");

                    b.Navigation("FilaProcedimentos");

                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("Gerente.Domain.Entities.Secretaria", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Servidores");

                    b.Navigation("Setores");

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
